# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ContainerServer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ContainerServer.proto',
  package='tr.com.argela.grpcserver',
  syntax='proto3',
  serialized_pb=_b('\n\x15\x43ontainerServer.proto\x12\x18tr.com.argela.grpcserver\"(\n\nDockerInfo\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"J\n\x06\x44ocker\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x32\n\x04info\x18\x02 \x01(\x0b\x32$.tr.com.argela.grpcserver.DockerInfo\"M\n\tContainer\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x34\n\ndockerlist\x18\x02 \x03(\x0b\x32 .tr.com.argela.grpcserver.Docker\"R\n\x14\x43ontainerListRequest\x12:\n\rcontainerlist\x18\x01 \x03(\x0b\x32#.tr.com.argela.grpcserver.Container\")\n\x15\x43ontainerListResponse\x12\x10\n\x08response\x18\x01 \x01(\x05\x32|\n\x0bSendService\x12m\n\x08\x63ontlist\x12..tr.com.argela.grpcserver.ContainerListRequest\x1a/.tr.com.argela.grpcserver.ContainerListResponse\"\x00\x42\x02P\x01\x62\x06proto3')
)




_DOCKERINFO = _descriptor.Descriptor(
  name='DockerInfo',
  full_name='tr.com.argela.grpcserver.DockerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='tr.com.argela.grpcserver.DockerInfo.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='tr.com.argela.grpcserver.DockerInfo.status', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=91,
)


_DOCKER = _descriptor.Descriptor(
  name='Docker',
  full_name='tr.com.argela.grpcserver.Docker',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='tr.com.argela.grpcserver.Docker.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='info', full_name='tr.com.argela.grpcserver.Docker.info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=167,
)


_CONTAINER = _descriptor.Descriptor(
  name='Container',
  full_name='tr.com.argela.grpcserver.Container',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='tr.com.argela.grpcserver.Container.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dockerlist', full_name='tr.com.argela.grpcserver.Container.dockerlist', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=246,
)


_CONTAINERLISTREQUEST = _descriptor.Descriptor(
  name='ContainerListRequest',
  full_name='tr.com.argela.grpcserver.ContainerListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='containerlist', full_name='tr.com.argela.grpcserver.ContainerListRequest.containerlist', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=330,
)


_CONTAINERLISTRESPONSE = _descriptor.Descriptor(
  name='ContainerListResponse',
  full_name='tr.com.argela.grpcserver.ContainerListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='tr.com.argela.grpcserver.ContainerListResponse.response', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=332,
  serialized_end=373,
)

_DOCKER.fields_by_name['info'].message_type = _DOCKERINFO
_CONTAINER.fields_by_name['dockerlist'].message_type = _DOCKER
_CONTAINERLISTREQUEST.fields_by_name['containerlist'].message_type = _CONTAINER
DESCRIPTOR.message_types_by_name['DockerInfo'] = _DOCKERINFO
DESCRIPTOR.message_types_by_name['Docker'] = _DOCKER
DESCRIPTOR.message_types_by_name['Container'] = _CONTAINER
DESCRIPTOR.message_types_by_name['ContainerListRequest'] = _CONTAINERLISTREQUEST
DESCRIPTOR.message_types_by_name['ContainerListResponse'] = _CONTAINERLISTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DockerInfo = _reflection.GeneratedProtocolMessageType('DockerInfo', (_message.Message,), dict(
  DESCRIPTOR = _DOCKERINFO,
  __module__ = 'ContainerServer_pb2'
  # @@protoc_insertion_point(class_scope:tr.com.argela.grpcserver.DockerInfo)
  ))
_sym_db.RegisterMessage(DockerInfo)

Docker = _reflection.GeneratedProtocolMessageType('Docker', (_message.Message,), dict(
  DESCRIPTOR = _DOCKER,
  __module__ = 'ContainerServer_pb2'
  # @@protoc_insertion_point(class_scope:tr.com.argela.grpcserver.Docker)
  ))
_sym_db.RegisterMessage(Docker)

Container = _reflection.GeneratedProtocolMessageType('Container', (_message.Message,), dict(
  DESCRIPTOR = _CONTAINER,
  __module__ = 'ContainerServer_pb2'
  # @@protoc_insertion_point(class_scope:tr.com.argela.grpcserver.Container)
  ))
_sym_db.RegisterMessage(Container)

ContainerListRequest = _reflection.GeneratedProtocolMessageType('ContainerListRequest', (_message.Message,), dict(
  DESCRIPTOR = _CONTAINERLISTREQUEST,
  __module__ = 'ContainerServer_pb2'
  # @@protoc_insertion_point(class_scope:tr.com.argela.grpcserver.ContainerListRequest)
  ))
_sym_db.RegisterMessage(ContainerListRequest)

ContainerListResponse = _reflection.GeneratedProtocolMessageType('ContainerListResponse', (_message.Message,), dict(
  DESCRIPTOR = _CONTAINERLISTRESPONSE,
  __module__ = 'ContainerServer_pb2'
  # @@protoc_insertion_point(class_scope:tr.com.argela.grpcserver.ContainerListResponse)
  ))
_sym_db.RegisterMessage(ContainerListResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('P\001'))

_SENDSERVICE = _descriptor.ServiceDescriptor(
  name='SendService',
  full_name='tr.com.argela.grpcserver.SendService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=375,
  serialized_end=499,
  methods=[
  _descriptor.MethodDescriptor(
    name='contlist',
    full_name='tr.com.argela.grpcserver.SendService.contlist',
    index=0,
    containing_service=None,
    input_type=_CONTAINERLISTREQUEST,
    output_type=_CONTAINERLISTRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SENDSERVICE)

DESCRIPTOR.services_by_name['SendService'] = _SENDSERVICE

# @@protoc_insertion_point(module_scope)
